//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageQueue.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessageQueue.Core.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgment is not configured for the queue..
        /// </summary>
        public static string AcknowledgmentIsNotConfiguredForQueue {
            get {
                return ResourceManager.GetString("AcknowledgmentIsNotConfiguredForQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange does not exist..
        /// </summary>
        public static string ExchangeDoesNotExist {
            get {
                return ResourceManager.GetString("ExchangeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to abandon message acknowledgment..
        /// </summary>
        public static string FailedToAbandonMessageAcknowledgment {
            get {
                return ResourceManager.GetString("FailedToAbandonMessageAcknowledgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to acknowledge message..
        /// </summary>
        public static string FailedToAcknowledgeMessage {
            get {
                return ResourceManager.GetString("FailedToAcknowledgeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check exchange existence..
        /// </summary>
        public static string FailedToCheckExchangeExistence {
            get {
                return ResourceManager.GetString("FailedToCheckExchangeExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check queue existence..
        /// </summary>
        public static string FailedToCheckQueueExistence {
            get {
                return ResourceManager.GetString("FailedToCheckQueueExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check if queue has message..
        /// </summary>
        public static string FailedToCheckQueueHasMessage {
            get {
                return ResourceManager.GetString("FailedToCheckQueueHasMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create exchange..
        /// </summary>
        public static string FailedToCreateExchange {
            get {
                return ResourceManager.GetString("FailedToCreateExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create queue..
        /// </summary>
        public static string FailedToCreateMessageQueue {
            get {
                return ResourceManager.GetString("FailedToCreateMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while creating ZeroMq socket..
        /// </summary>
        public static string FailedToCreateZeroMqSocket {
            get {
                return ResourceManager.GetString("FailedToCreateZeroMqSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize Json bytes..
        /// </summary>
        public static string FailedToDeserializeJsonBytes {
            get {
                return ResourceManager.GetString("FailedToDeserializeJsonBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize Json string..
        /// </summary>
        public static string FailedToDeserializeJsonString {
            get {
                return ResourceManager.GetString("FailedToDeserializeJsonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract constants through reflection..
        /// </summary>
        public static string FailedToExtractConstantFields {
            get {
                return ResourceManager.GetString("FailedToExtractConstantFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize message queue..
        /// </summary>
        public static string FailedToInitializeMessageQueue {
            get {
                return ResourceManager.GetString("FailedToInitializeMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate InboundFaF..
        /// </summary>
        public static string FailedToInstantiateInboundFaFMq {
            get {
                return ResourceManager.GetString("FailedToInstantiateInboundFaFMq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate InboundRaR..
        /// </summary>
        public static string FailedToInstantiateInboundRaRMq {
            get {
                return ResourceManager.GetString("FailedToInstantiateInboundRaRMq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate OutboundFaF..
        /// </summary>
        public static string FailedToInstantiateOutboundFaF {
            get {
                return ResourceManager.GetString("FailedToInstantiateOutboundFaF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate OutboundRaR..
        /// </summary>
        public static string FailedToInstantiateOutboundRaRMq {
            get {
                return ResourceManager.GetString("FailedToInstantiateOutboundRaRMq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred in message receiver handler..
        /// </summary>
        public static string FailedToReceiveMessage {
            get {
                return ResourceManager.GetString("FailedToReceiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred in request message receiver handler..
        /// </summary>
        public static string FailedToReceiveRequestMessage {
            get {
                return ResourceManager.GetString("FailedToReceiveRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred in response message receiver handler..
        /// </summary>
        public static string FailedToReceiveResponseMessage {
            get {
                return ResourceManager.GetString("FailedToReceiveResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send message..
        /// </summary>
        public static string FailedToSendMessage {
            get {
                return ResourceManager.GetString("FailedToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send response message..
        /// </summary>
        public static string FailedToSendResponseMessage {
            get {
                return ResourceManager.GetString("FailedToSendResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to serialize object into Json bytes..
        /// </summary>
        public static string FailedToSerializeObjectIntoJsonBytes {
            get {
                return ResourceManager.GetString("FailedToSerializeObjectIntoJsonBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to serialize object into Json string..
        /// </summary>
        public static string FailedToSerializeObjectIntoJsonString {
            get {
                return ResourceManager.GetString("FailedToSerializeObjectIntoJsonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start receiving messages..
        /// </summary>
        public static string FailedToStartReceivingMessage {
            get {
                return ResourceManager.GetString("FailedToStartReceivingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start receiving requests..
        /// </summary>
        public static string FailedToStartReceivingRequest {
            get {
                return ResourceManager.GetString("FailedToStartReceivingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop receiving messages..
        /// </summary>
        public static string FailedToStopReceivingMessage {
            get {
                return ResourceManager.GetString("FailedToStopReceivingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop receiving requests..
        /// </summary>
        public static string FailedToStopReceivingRequest {
            get {
                return ResourceManager.GetString("FailedToStopReceivingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse configuration due to unknown error..
        /// </summary>
        public static string GeneralConfigurationParsingError {
            get {
                return ResourceManager.GetString("GeneralConfigurationParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration parameter value (parameter: {0})..
        /// </summary>
        public static string InvalidValueForConfigurationParameter {
            get {
                return ResourceManager.GetString("InvalidValueForConfigurationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ZeroMq socket type..
        /// </summary>
        public static string InvalidZeroMqSocketType {
            get {
                return ResourceManager.GetString("InvalidZeroMqSocketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message queue has not been initialized..
        /// </summary>
        public static string MessageQueueIsNotInitialized {
            get {
                return ResourceManager.GetString("MessageQueueIsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has been returned from the queue..
        /// </summary>
        public static string MessageReturnedFromQueue {
            get {
                return ResourceManager.GetString("MessageReturnedFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace address is required in configuration for the requested operation..
        /// </summary>
        public static string MissingNamespaceAddressInConfiguration {
            get {
                return ResourceManager.GetString("MissingNamespaceAddressInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required configuration parameter (parameter: {0})..
        /// </summary>
        public static string MissingRequiredConfigurationParameter {
            get {
                return ResourceManager.GetString("MissingRequiredConfigurationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported parameter(s) provided..
        /// </summary>
        public static string NotSupportedConfigurationParameters {
            get {
                return ResourceManager.GetString("NotSupportedConfigurationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter (parameter: {0}) is not applicable in the current configuration..
        /// </summary>
        public static string ParameterNotApplicationInCurrentConfiguration {
            get {
                return ResourceManager.GetString("ParameterNotApplicationInCurrentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter (parameter: {0}) is required in current configuration..
        /// </summary>
        public static string ParameterRequiredInCurrentConfiguration {
            get {
                return ResourceManager.GetString("ParameterRequiredInCurrentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue does not exist..
        /// </summary>
        public static string QueueDoesNotExist {
            get {
                return ResourceManager.GetString("QueueDoesNotExist", resourceCulture);
            }
        }
    }
}
